### ISSUE TITLE
Can't find Buyer by email.

### ISSUE THREAD

**Issue by davidgrieser** [balanced/balanced-ruby#15]
There isn't a method `Marketplace#find_buyer` to get a buyer account from the Balanced system.

**Comment by zealoushacker** [comment]
While there is a `Balanced::Resource.find` method, it always expects the URI. I think it definitely makes sense to have a more generic set of finder methods to be able to search by various attributes (much like Rails provides `find_by_x` methods on `ActiveRecord` and `ActiveResource`).

**Comment by mahmoudimus** [comment]
That definitely makes sense. I'm working on something similar.

**Comment by mahmoudimus** [comment]
So @alexnotov rails provides something like `named_scopes`, which essentially is what would be implemented here. However, I really like our python client's way of filtering: https://github.com/bninja/wac/blob/master/tests.py#L758

So, essentially we have a robust way to filter where the filtering operation is encoded into the string between `[]` on teh key, e.g. `amount[<]=1500` which translates to `amount < 1500`.

What would you think is the proper way to express this in idiomatic Ruby?

**Comment by zealoushacker** [comment]
@mahmoudimus You wouldn't use named scopes to implement this, since you don't have access to that outside of rails. Plus that's tied to the ORM. Though I think you're probably just referring to the idea behind named scopes and the where clause implementation they built for that.

The filtering concept in py seems really neat, but can possibly be confusing in terms of readability - e.g. `amount[<]=1500` may accidentally be read as `amount <= 1500`.

[edited after I answered my own question by looking at the reference https://github.com/bninja/wac/blob/master/tests.py#L758]

**Comment by zealoushacker** [comment]
In order to answer your question, I'd need to know what ruby object(s) we'd be operating on... It sounds like it would be an array of hashes and we'd be filtering on the value of a key, irrespective of the data type of the value, and considering that at a key we may indeed find an array of values, on which we would possibly want to do a range filter... going further, we'd want to be able to concatenate the filters? Lots of questions here...

**Comment by mahmoudimus** [comment]
I think it's important to concatenate the filters -- the way we solved this in our python client was by having a `query` attribute that essentially returned a `Queryable` object that took the resource to operate on.

Regarding knowing the fields ahead of time, i think it would make sense if one passes the values through directly, leaving the server to validate whether or not a field actually exists on a resource or not. The range filters would probably translate to a `between` or a `contains` as the operator: e.g. `roles[contains]=buyer`.

Any examples in the wild?

**Comment by zealoushacker** [comment]
I would like to step back and ask a few questions:

What sort of data does your typical customer (balanced API implementer) need on a regular basis and how would they like to query it the majority of the time?

Are 80%+ of your customers going to want to operate on single objects or simple lists, queried via a basic attribute list, like so: `Account.find_by_email`, or `Account.find(7)`, or `Account.find([7, 8, 9])`, etc.?

If the latter is true, do you want to satisfy those needs or figure out a possibly graceful, but time consuming solution to that querying problem?

**Comment by zealoushacker** [comment]
As far as examples in the wild: http://guides.rubyonrails.org/active_record_querying.html :metal:

Again though, the above is for doing complicated querying that translates into SQL. It's not for building an API tier that clearly delineates the boundaries between your system and ours.

**Comment by zealoushacker** [comment]
zzz... seeing as how this has been stale for a couple of days, I'd like to add another comment:

Remember, you guys are building this gem for the rails community. Don't reinvent the wheel. Follow the patterns that we are used to, and we'll be happy campers. Finder methods are obvious :) 

This doesn't mean that there's no room for change and innovation. It just means that you should think about what 80% of the Rails community would want first and provide it, and then innovate. :metal:

**Comment by mahmoudimus** [comment]
Fixed in gem ~> 0.3.4
