### ISSUE TITLE
Account.debit does not honor documented card_uri field

### ISSUE THREAD

**Issue by phallguy** [balanced/balanced-ruby#58]
When creating a debit through the Account.debit method, passing a card_uri parameter as documented in the API reference, that value is not passed to the Debit object. This is a problem when multiple cards are stored for a user (for example they use one card, it's declined due to ISF, then provide a second card).

**Comment by phallguy** [comment]
It also doesn't honor the merchant_uri field.

**Comment by mjallday** [comment]
Hey @phallguy 

If you look at the [source code](https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/account.rb#L40), you can see that it expects the `source_uri` param rather than `card_uri`. This is more portable since you won't need to change the param name if you debited an alternate funding instrument such as a bank account if Balanced supports these in the future.

Here's an example you can use:

```
require 'balanced'

api_key = Balanced::ApiKey.new.save
Balanced.configure(api_key.secret)
marketplace = Balanced::Marketplace.new.save

card = Balanced::Card.new(
  :card_number => "5105105105105100",
  :expiration_month => "12",
  :expiration_year => "2015",
).save
card2 = Balanced::Card.new(
  :card_number => "341111111111111",
  :expiration_month => "12",
  :expiration_year => "2015",
).save
card3 = Balanced::Card.new(
  :card_number => "4111111111111111",
  :expiration_month => "12",
  :expiration_year => "2015",
).save

buyer = marketplace.create_buyer(
    :email_address => "buyer@example.org",
    :card_uri => card.uri
)
buyer.add_card(card2.uri)
buyer.add_card(card3.uri)

debit1 = buyer.debit(
    :amount => 53000,
    :source_uri => card.uri
)

debit2 = buyer.debit(
    :amount => 53000,
    :source_uri => card2.uri
)

debit3 = buyer.debit(
    :amount => 53000,
    :source_uri => card3.uri
)

raise 'bug!' if debit1.source.brand != 'MasterCard'
raise 'bug!' if debit2.source.brand != 'American Express'
raise 'bug!' if debit3.source.brand != 'Visa'
```

In regards to the `merchant_uri` param, try passing it through in the meta field:

```
debit4 = buyer.debit(
  :amount => 53000,
  :meta => { :merchant_uri => '/v1/xxxxxx'})

puts debit4.meta
```

This doesn't seem clear in the [documentation](https://www.balancedpayments.com/docs/overview?language=bash#associating-debits-charges-with-a-merchant) so we'll get that fixed up. Thanks for bringing it to our attention!

**Comment by seejohnrun** [comment]
So glad I just saw this - the documentation should definitely be cleared up and card_uri removed from the left side

**Comment by mjallday** [comment]
I've [created an issue in our documentation repo](https://github.com/balanced/balanced-docs/issues/21) to better address how to associate merchant's and debits.

@seejohnrun To be clear: the `card_uri` param _will work_ with the API, it's just the balanced-ruby client doesn't support it.

**Comment by seejohnrun** [comment]
Right - just a bit confusing because in the "Ruby" mode on the documentation it is still listed on the left side and there is no mention of it working or not working - or even what source_uri is

Thanks guys - and again, amazing service :)
